<?php

namespace Acme\HelloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findProductsByPage($page)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AcmeHelloBundle:Product p ORDER BY p.name ASC')
            ->getResult();
    }

    public function deleteProductById($id)
    {
        $em = $this->getEntityManager();
        $product = $em->find('AcmeHelloBundle:Product', $id);
        $em->remove($product);
        $em->flush();

        //return $result;

        /* $result = $this->getEntityManager()
            ->createQuery('DELETE p FROM AcmeHelloBundle:Product p WHERE p.id = ?')->setParameter(1, $id)
            ->getResult();
        return $result; */
    }
}
